
CREATE DATABASE FRUITSHOP
GO
USE FRUITSHOP
GO

CREATE TABLE ACCOUNTS(
	ID INT PRIMARY KEY IDENTITY,
	USERNAME NVARCHAR(50),
	PASSWORD NVARCHAR(50),
	FULLNAME NVARCHAR(50),
	EMAIL NVARCHAR(MAX),
	ADDRESS NVARCHAR(MAX),
	PHONE NVARCHAR(11),
	AVATAR NVARCHAR(MAX),
	ISADMIN INT,
	STATUS INT
)
GO
CREATE TABLE ACCOUNTREVIEWS(
	ID INT PRIMARY KEY IDENTITY,
	PRODUCTID INT,
	ACCOUNTID INT,
	CONTENT NVARCHAR(MAX),
	LIKES INT,
	POSTEDDATE DATETIME,
	STATUS INT
	FOREIGN KEY (ACCOUNTID) REFERENCES ACCOUNTS(ID)
)
GO
CREATE TABLE PRODUCTS(
	ID INT PRIMARY KEY IDENTITY,
	SKU NVARCHAR(50),
	NAME NVARCHAR(50),
	PRICE FLOAT,
	STOCK INT,
	UNIT NVARCHAR(10),
	DESCRIPTION NVARCHAR(50),
	IMAGE NVARCHAR(MAX),
	STATUS INT
)
GO
CREATE TABLE CARTS(
	ID INT PRIMARY KEY IDENTITY,
	ACCOUNTID INT,
	PRODUCTID INT,
	QUANTITY INT,
)
GO
CREATE TABLE VOUCHERS(
	ID INT PRIMARY KEY IDENTITY,
	CODE NVARCHAR(50),
	PRODUCTID INT,
	NAME NVARCHAR(50),
	REDUCE INT,
	STARTDATE DATETIME,
	ENDDATE DATETIME,
	LIMIT INT,
	STATUS INT,
	FOREIGN KEY (PRODUCTID) REFERENCES PRODUCTS(ID)
)
GO
CREATE TABLE INVOICES(
	ID INT PRIMARY KEY IDENTITY,
	CODE NVARCHAR(50),
	ISPAID INT,
	ORDERDATE DATETIME,
	SHIPPINGNAME NVARCHAR(50),
	SHIPPINGPHONE NVARCHAR(50),
	SHIPPINGADDRESS NVARCHAR(50),
	TOTAL FLOAT,
	ACCOUNTID INT,
	VOUCHERID INT,
	STATUS INT
	FOREIGN KEY (ACCOUNTID) REFERENCES ACCOUNTS(ID)
)
GO
CREATE TABLE INVOICEDETAILS(
	ID INT PRIMARY KEY IDENTITY,
	INVOICEID INT,
	PRODUCTID INT,
	QUANTITY INT,
	UNITPRICE INT,
	FOREIGN KEY (INVOICEID) REFERENCES INVOICES(ID),
	FOREIGN KEY (PRODUCTID) REFERENCES PRODUCTS(ID)
)
GO

DELETE FROM ACCOUNTS;
DBCC CHECKIDENT ('FRUITSHOP.dbo.ACCOUNTS', RESEED, 0);
GO
DELETE FROM ACCOUNTREVIEWS;
DBCC CHECKIDENT ('FRUITSHOP.dbo.ACCOUNTREVIEWS', RESEED, 0);
GO
DELETE FROM PRODUCTS;
DBCC CHECKIDENT ('FRUITSHOP.dbo.PRODUCTS', RESEED, 0);
GO
DELETE FROM CARTS;
DBCC CHECKIDENT ('FRUITSHOP.dbo.CARTS', RESEED, 0);
GO
DELETE FROM VOUCHERS;
DBCC CHECKIDENT ('FRUITSHOP.dbo.VOUCHERS', RESEED, 0);
GO
DELETE FROM INVOICES;
DBCC CHECKIDENT ('FRUITSHOP.dbo.INVOICES', RESEED, 0);
GO
DELETE FROM INVOICEDETAILS;
DBCC CHECKIDENT ('FRUITSHOP.dbo.INVOICEDETAILS', RESEED, 0);
GO


INSERT INTO Accounts (Username, Password, Email, Phone, Address, FullName, IsAdmin, Avatar, Status) VALUES ('ngvuminhLong', 'admin', 'admin@Eshop.com', '01234567890', N'Tp.Hồ Chí Minh', N'Nguyễn Vũ Minh Long', 1, 'admin.jpg', 1);
INSERT INTO Accounts (Username, Password, Email, Phone, Address, FullName, IsAdmin, Avatar, Status) VALUES ('htannghia', '123456', '2@gmail.com', '0905486957', N'Đà Nẵng', N'huỳnh tấn nghĩa', 0, 'john.jpg', 1);
INSERT INTO Accounts (Username, Password, Email, Phone, Address, FullName, IsAdmin, Avatar, Status) VALUES ('nghoaichuong', '123456', '1@gmail.com', '0904863125', N'Tp.Hồ Chí Minh', N'Nguyễn hoài chương', 0, 'haha.jpg', 1);
INSERT INTO Accounts (Username, Password, Email, Phone, Address, FullName, IsAdmin, Avatar, Status) VALUES ('ngthanhle', '123456', '3@gmail.com', '0459123845', N'Nha Trang', N'Nguyễn thành lễ', 0, 'longvic.jpg', 1);
INSERT INTO Accounts (Username, Password, Email, Phone, Address, FullName, IsAdmin, Avatar, Status) VALUES ('hovantuan', '123456', '4@gmail.com', '0987654321', N'Huế', N'hồ văn tuân', 0, 'customer.jpg', 1);

INSERT INTO Products (SKU, Name, Description, Price, Stock, Unit, Image, Status) VALUES ('WT3WPGZ9BTWB', N'Sầu riêng', N'Rất ngon', 45000, 40, 'KG', '1.jpg', 1);
INSERT INTO Products (SKU, Name, Description, Price, Stock, Unit, Image, Status) VALUES ('98IOWWXWYVQ4', N'Sầu riêng', N'Rất ngon', 51000, 15,'KG', '2.jpg', 1);
INSERT INTO Products (SKU, Name, Description, Price, Stock, Unit,  Image, Status) VALUES ('21RH48HRFXX8', N'Sầu riêng', N'Rất ngon', 59000, 29,'KG', '3.jpg', 1);
INSERT INTO Products (SKU, Name, Description, Price, Stock, Unit,  Image, Status) VALUES ('QOXYSDE605P5', N'Sầu riêng', N'Rất ngon', 53000, 1,'KG', '4.jpg', 1);
INSERT INTO Products (SKU, Name, Description, Price, Stock, Unit,  Image, Status) VALUES ('6YI6TZ3JPO1L', N'Sầu riêng', N'Rất ngon', 52000, 36,'KG', '5.jpg', 1);

INSERT INTO Carts (AccountId, ProductId, QUANTITY) VALUES (1, 1, 2);
INSERT INTO Carts (AccountId, ProductId, QUANTITY) VALUES (2, 1, 4);
INSERT INTO Carts (AccountId, ProductId, QUANTITY) VALUES (5, 2, 2);
INSERT INTO Carts (AccountId, ProductId, QUANTITY) VALUES (5, 6, 1);

 INSERT INTO Invoices (Code, AccountId, ORDERDATE, ISPAID,SHIPPINGNAME,ShippingAddress, ShippingPhone, Total, Status) VALUES ('299541176755', 5, '2020-01-15 15:06:12', 1,N'BẠN PHONE' ,N'Quận 3, Tp.HCM', '0987654321', 618000, 1);
 INSERT INTO Invoices (Code, AccountId, ORDERDATE, ISPAID, SHIPPINGNAME,ShippingAddress, ShippingPhone, Total, Status) VALUES ('527777447269', 2, '2020-01-16 10:30:19', 1,N'BẠN PHONE',N'Quận 1, Tp.HCM', '0983564782', 167000, 1);
 INSERT INTO Invoices (Code, AccountId, ORDERDATE, ISPAID, SHIPPINGNAME,ShippingAddress, ShippingPhone, Total, Status) VALUES ('228448970415', 2, '2020-01-18 18:02:07',0 ,N'BẠN PHONE',N'Quận 5, Tp.HCM', '0983564782', 570000, 1);
 INSERT INTO Invoices (Code, AccountId, ORDERDATE, ISPAID,SHIPPINGNAME ,ShippingAddress, ShippingPhone, Total, Status) VALUES ('827349270900', 2, '2020-01-20 20:35:53',1,N'BẠN PHONE',N'Quận 1, Tp.HCM', '0983564782', 480000, 0);
 INSERT INTO Invoices (Code, AccountId, ORDERDATE, ISPAID, SHIPPINGNAME,ShippingAddress, ShippingPhone, Total, Status) VALUES ('127745305853', 3, '2020-01-24 08:20:17', 0,N'BẠN PHONE',N'Quận 7, Tp.HCM', '0905785346', 829000, 1);
 INSERT INTO Invoices (Code, AccountId, ORDERDATE, ISPAID, SHIPPINGNAME,ShippingAddress, ShippingPhone, Total, Status) VALUES ('074407650817', 4, '2020-01-24 09:00:52',1 ,N'BẠN PHONE',N'Nha Trang', '0459123845', 478000, 0);
 INSERT INTO Invoices (Code, AccountId, ORDERDATE, ISPAID,SHIPPINGNAME ,ShippingAddress, ShippingPhone, Total, Status) VALUES ('611108375524', 3, '2020-01-28 14:20:54',0 ,N'BẠN PHONE',N'Quận 7, Tp.HCM', '0905785346', 642000, 1);
 INSERT INTO Invoices (Code, AccountId, ORDERDATE, ISPAID, SHIPPINGNAME,ShippingAddress, ShippingPhone, Total, Status) VALUES ('178291648473', 4, '2020-01-24 18:29:07', 0,N'BẠN PHONE',N'Nha Trang', '0459123845', 327000, 1);

INSERT INTO InvoiceDetails (InvoiceId, ProductId, QUANTITY, UnitPrice) VALUES (1, 1, 2, 45000);
INSERT INTO InvoiceDetails (InvoiceId, ProductId, QUANTITY, UnitPrice) VALUES (1, 3, 5, 59000);
INSERT INTO InvoiceDetails (InvoiceId, ProductId, QUANTITY, UnitPrice) VALUES (1, 4, 1, 53000);

SELECT * FROM ACCOUNTS
SELECT * FROM PRODUCTS
SELECT * FROM CARTS
SELECT * FROM INVOICES
SELECT * FROM INVOICEDETAILS